version: '3.8'

services:
  webgis:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped
    container_name: wdias-webgis